### ISSUE TITLE
not activating!

### ISSUE THREAD

**Issue by dev0zero** [chiptuneXT/DoulCi-server2#5]
Hi, i made all how explains.
1. Download Dulci Server 2
2. Download and install Xampp 
3. Put scripts to htdocs 
4. modify a hosts to local albert
5. start itunes it show error about server and give me error message 
The iphone could not be activated because the activation information was invalid. Please try again later

and show in iTunes data from server.
Demo activation is done! Activation Info: 
here is iphone 4[s]  data 
so i have some questions:
1. what i'm done wrong?
2. Script is still usable? i use iTunes 12.2.2.25  (win x64)
3. i understand that i tunes generates activation-info _POST and send, server must answer to client with good activation, maybe i am doing something wrong.
4. What means true certificates and how with them to work.

i need some explane, please can you help me.

**Comment by michaelaous** [comment]
yeah you need to find itdetector file and put into itune programe on computer after close the itunes and reopen and backup. it done

**Comment by KYMabuzo** [comment]
how?

**Comment by michaelaous** [comment]
in C:\Program Files\iTunes\iTunes.Resources

**Comment by KYMabuzo** [comment]
where can I find itdetector file ? .. thru online?

**Comment by chiptuneXT** [comment]
You need replace demo certs+keys for genuine one. Without it - impossible.
