### ISSUE TITLE
Device cannot be activated

### ISSUE THREAD

**Issue by Yukurii** [chiptuneXT/DoulCi-server2#7]
I've received error information below from iTunes when I was testing the service:
Warning: openssl_x509_export(): cannot get cert from parameter 1 in D:\xampp\htdocs\deviceservices\deviceActivation.php on line 87
I'm appreciate if you can provide some solutions for the problem.
Thanks!

**Comment by chiptuneXT** [comment]
Hello. You need private keys for this certs. Without it you can't activate your device. Special demo certs+keys built in, but device doesn't trust them. This project only for educational and entertainment purposes (how activation server working and like that).
